//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EF
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class PrintManagementSystemEntities : DbContext
    {
        public PrintManagementSystemEntities()
            : base("name=PrintManagementSystemEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Configuration> Configuration { get; set; }
        public virtual DbSet<ConfigurationType> ConfigurationType { get; set; }
        public virtual DbSet<Customer> Customer { get; set; }
        public virtual DbSet<ItemDisplayConfig> ItemDisplayConfig { get; set; }
        public virtual DbSet<JobProcessType> JobProcessType { get; set; }
        public virtual DbSet<OrderConfiguration> OrderConfiguration { get; set; }
        public virtual DbSet<OrderItem> OrderItem { get; set; }
        public virtual DbSet<PaperGSM> PaperGSM { get; set; }
        public virtual DbSet<PaperQuality> PaperQuality { get; set; }
        public virtual DbSet<PaperSide> PaperSide { get; set; }
        public virtual DbSet<PrintingColour> PrintingColour { get; set; }
        public virtual DbSet<ProductItem> ProductItem { get; set; }
        public virtual DbSet<User> User { get; set; }
        public virtual DbSet<UserRole> UserRole { get; set; }
        public virtual DbSet<UserSecurityQuestion> UserSecurityQuestion { get; set; }
        public virtual DbSet<LedgerFalio> LedgerFalio { get; set; }
        public virtual DbSet<PaperSize> PaperSize { get; set; }
    }
}
