//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class ItemDisplayConfig
    {
        public int ItemDisplayConfigId { get; set; }
        public int ProductItemId { get; set; }
        public bool PaperGSM { get; set; }
        public bool PaperColour { get; set; }
        public bool PaperSize { get; set; }
        public bool PaperQuality { get; set; }
        public bool PaperSides { get; set; }
        public bool LedgerFalio { get; set; }
        public bool AdditionalPaperCount { get; set; }
        public bool AdditionalPaperSize { get; set; }
        public bool AdditonalPaperGSM { get; set; }
        public bool PerBookBillCount { get; set; }
    
        public virtual ProductItem ProductItem { get; set; }
    }
}
